server:
  port: 2175

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:h2:tcp://localhost/C:\Work\DB\payment-service
    username: sa
    password: 1234
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  cloud:
    config:
      enabled: false
  sql:
    init:
      mode: always

eureka:
#  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
