server:
  port: 8010

spring:
  application:
    name: matching-service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
