server:
  port: 8088

spring:
  config:
    application:
      name: product-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/study/devtalk/DevTalk-BE
    username: sa
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true # Eureka ????? ?????? ??? ????? ??? ???? ???? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka