spring:
  application:
    name: common-service

jwt:
  token:
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
    access-token-validity-in-seconds: 1800	# ?
    refresh-token-validity-in-seconds: 259200	# ?