#API-Gateway 포트번호 : 클라이언트는 모든 요청을 API-Gateway로 보냄
server:
  port: 8800

#각 서비스들의 요청과 해당 MS를 LoadBalancing 하기 위해 eureka 서버 등록
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: apigateway-service
  cloud:
    gateway: #라우팅 설정
      default-filters:
      routes:
        - id: member-service
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/signup/**, /member/login
          filters:
            - RemoveRequestHeader=Cookie
#            - RewritePath=/member/(?<segment>,*),/$\{segment}
        - id: member-service-auth
          uri: lb://MEMBER-SERVICE
          predicates:
            - Path=/member/**
          filters:
            - RemoveRequestHeader=Cookie
            - AuthorizationHeaderFilter
#        - id: member-service-health-check
#          uri: lb://MEMBER-SERVICE
#          predicates:
#            - Path=/member-service/member/signup/health_check
        - id: payment-service
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
        - id: matching-service
          uri: lb://MATCHING-SERVICE
          predicates:
            - Path=/matching/**
        - id: user_route
          uri: http://localhost:9999
          metadata:
            sampleKey: sampleValue    # 필터에서 사용 가능한 별도 파라미터
          predicates:
            - After=2022-01-01T08:00:00.000+09:00[Asia/Seoul]
            - Before=2022-12-31T22:00:00.000+09:00[Asia/Seoul]
            - Between=2022-01-01T08:00:00.000+09:00[Asia/Seoul], 2022-12-31T22:00:00.000+09:00[Asia/Seoul]
            - Cookie=chocolate, ch.p
            - Header=X-Request-Id, \d+
            - Host=**.example.com,**.example.org  # Host Header 기반
            - Method=GET,POST
            - Path=/user/{segment}                # Path 기반              - Query=green
            - Query=debug, true
            - RemoteAddr=192.168.1.1/24
        - id: user_route
          uri: lb://user
          predicates:
            - Path=/user/**
          filters:
            - AddRequestHeader=X-Request-red, blue
            - AddRequestParameter=red, blue
            - AddResponseHeader=X-Response-Red, Blue
            - PrefixPath=/v1
            - RedirectTo=302, https://acme.org
            - RewritePath=/user/?(?<segment>.*), /$\{segment}
            - SetPath=/{segment}

jwt:
  token:
    secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK