server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  :application:
    name: dtk-gateway
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: dtk-board-api
          uri: http://localhost:8081/
          predicates:
            - Path=/dtk-board-api/**
        - id: config
          uri: http://localhost:8082/
          predicates:
            - Path=/config/**
          filters:
            - AddRequestHeader=second-request, second-request-header
            - AddResponseHeader=second-response, second-response-header
        - id: dtk-consultation-api
          uri: http://localhost:8083/
          predicates:
            - Path=/dtk-consultation-api/**
        - id: discovery
          uri: http://localhost:8084/
          predicates:
            - Path=/discovery/**
        - id: dtk-gateway
          uri: http://localhost:8085/
          predicates:
            - Path=/dtk-gateway/**
        - id: dtk-member-api
          uri: http://localhost:8086/
          predicates:
            - Path=/dtk-member-api/**
        - id: dtk-payment-api
          uri: http://localhost:8087/
          predicates:
            - Path=/dtk-payment-api/**
        - id: dtk-product-api
          uri: http://localhost:8088/
          predicates:
            - Path=/dtk-product-api/**
